version: "3.8"

services:
  posgres-event:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=events_db
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
    ports:
      - "5435:5432"